version: '3.9'
services:
  spring:
    container_name: "spring"
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.gradle:/root/.gradle
    ports:
      - "9000:9000"
    environment:
      MARIADB_ADDRESS: mariadb
      MARIADB_USERNAME: root
      MARIADB_PASSWORD: root
    depends_on:
      - mariadb
#    command: gradle -D spring.profiles.active=docker bootrun
    command: gradle -D spring.profiles.active=docker test
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
    container_name: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT:-8082}:80
    environment:
      UPLOAD_LIMIT: 1G
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    depends_on:
      - mariadb