version: "3.9"
services:
  mysql:
    image: mariadb:10.4.13
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_USER=${DATABASE_USER:-root}
      - MYSQL_PASSWORD={DATABASE_PASSWORD:-password}
      # - MYSQL_DATABASE={DATABASE_NAME:-test}
    restart: always
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
    container_name: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT:-8082}:80
    environment:
      UPLOAD_LIMIT: 1G
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    depends_on:
      - mysql
