INSERT INTO SONDAGE (id_personne, nom,prenom,mail,code_postal,ville,date_reponse) VALUES (NEXT VALUE FOR SONDAGE_SEQ,'Sophie','Boucher','sophie.boucher@gmail.com','67204','Pierre','2003-10-06');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,25956);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,25207);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,27005);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,20217);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,19437);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,25598);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,12812);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,40303);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,25531);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,28105);

INSERT INTO SONDAGE (id_personne, nom,prenom,mail,code_postal,ville,date_reponse) VALUES (NEXT VALUE FOR SONDAGE_SEQ,'Lorraine','Vallet','lorraine.vallet@gmail.com','67110','Vincent','2003-10-06');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,26128);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,31067);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,20802);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,24679);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,22001);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,25914);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,36037);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,11219);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,13112);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,8081);

INSERT INTO SONDAGE (id_personne, nom,prenom,mail,code_postal,ville,date_reponse) VALUES (NEXT VALUE FOR SONDAGE_SEQ,'Alfred','Godard','alfred.godard@gmail.com','57535','Berger','2003-10-06');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,25216);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,76057);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,39233);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,20280);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,9101);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,15202);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,10001);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,13067);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,20038);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,10018);

