INSERT INTO SONDAGE (id_personne, nom,prenom,mail,code_postal,ville,date_reponse) VALUES (NEXT VALUE FOR SONDAGE_SEQ,'Frédérique','Labbe-Bouvet','frederique.labbe-bouvet@gmail.com','23190','SantosBourg','2023-02-17');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,26154);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,15035);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,7117);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,11088);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,11052);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,1021);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,24015);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,19694);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,4037);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,31076);

INSERT INTO SONDAGE (id_personne, nom,prenom,mail,code_postal,ville,date_reponse) VALUES (NEXT VALUE FOR SONDAGE_SEQ,'Charlotte-Anne','Evrard','charlotte-anne.evrard@gmail.com','13380','Ribeiro','2023-02-17');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,11021);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,25038);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,26154);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,26244);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,1031);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,9010);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,36206);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,1000);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,31104);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,4038);

INSERT INTO SONDAGE (id_personne, nom,prenom,mail,code_postal,ville,date_reponse) VALUES (NEXT VALUE FOR SONDAGE_SEQ,'Claudine-Capucine','Blondel','claudine-capucine.blondel@gmail.com','50100','Nguyen','2023-02-17');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,6122);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,11035);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,20210);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,6910);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,18353);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,22502);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,2034);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,23494);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,32014);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = 'SONDAGE_SEQ') - 1 ,20210);

