-- ---------------------------------------------------------------------------
-- ------------------------------- CATEGORIES -------------------------------
-- ---------------------------------------------------------------------------
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1,'Entrées et plats composés','CATEGORIE',NULL);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(2,'Fruits, légumes, légumineuses et oléagineux','CATEGORIE',NULL);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(3,'Pâtes diverses, produits céréaliers','CATEGORIE',NULL);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(4,'Viandes, œufs, poissons et assimilés','CATEGORIE',NULL);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(5,'Produits laitiers et assimilés','CATEGORIE',NULL);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(6,'Eaux et autres boissons','CATEGORIE',NULL);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(7,'Produits sucrés','CATEGORIE',NULL);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(8,'Glaces et sorbets','CATEGORIE',NULL);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(9,'Matières grasses','CATEGORIE',NULL);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10,'Aides culinaires et ingrédients divers','CATEGORIE',NULL);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(11,'Aliments infantiles','CATEGORIE',NULL);
-- ---------------------------------------------------------------------------
-- ---------------------------- CHILD CATEGORIES ----------------------------
-- ---------------------------------------------------------------------------
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(103,'Plats composés','SOUSCATEGORIE',1);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(106,'Feuilletées et autres entrées','SOUSCATEGORIE',1);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(102,'Soupes','SOUSCATEGORIE',1);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(105,'Sandwichs','SOUSCATEGORIE',1);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(104,'Pizzas, tartes et crêpes salées','SOUSCATEGORIE',1);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(101,'Salades composées et crudités','SOUSCATEGORIE',1);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(204,'Fruits','SOUSCATEGORIE',2);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(205,'Fruits à coque et graines oléagineuses','SOUSCATEGORIE',2);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(201,'Légumes','SOUSCATEGORIE',2);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(202,'Pommes de terre et autres tubercules','SOUSCATEGORIE',2);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(203,'Légumineuses','SOUSCATEGORIE',2);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(301,'Pâtes, riz et céréales','SOUSCATEGORIE',3);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(305,'Pates et farines','SOUSCATEGORIE',3);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(302,'Pains et assimilés','SOUSCATEGORIE',3);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(303,'Biscuits apéritifs','SOUSCATEGORIE',3);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(401,'Viandes cuites','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(409,'Produits à base de poissons et produits de la mer','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(402,'Viandes crues','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(406,'Poissons crus','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(403,'Charcuteries et assimilés','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(405,'Poissons cuits','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(407,'Mollusques et crustacés cuits','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(404,'Autres produits à base de viande','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(411,'Substitus de produits carnés','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(408,'Mollusques et crustacés crus','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(410,'Œufs','SOUSCATEGORIE',4);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(503,'Fromages et assimilés','SOUSCATEGORIE',5);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(502,'Produits laitiers frais et assimilés','SOUSCATEGORIE',5);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(504,'Crèmes et spécialités à base de crème','SOUSCATEGORIE',5);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(501,'Laits','SOUSCATEGORIE',5);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(603,'Boisson alcoolisées','SOUSCATEGORIE',6);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(602,'Boissons sans alcool','SOUSCATEGORIE',6);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(601,'Eaux','SOUSCATEGORIE',6);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(709,'Gâteaux et pâtisseries','SOUSCATEGORIE',7);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(702,'Chocolats et produits à base de chocolat','SOUSCATEGORIE',7);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(706,'Biscuits sucrés','SOUSCATEGORIE',7);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(708,'Barres céréalières','SOUSCATEGORIE',7);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(707,'Céréales de petit-déjeuner','SOUSCATEGORIE',7);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(703,'Confiseries non chocolatées','SOUSCATEGORIE',7);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(705,'Viennoiseries','SOUSCATEGORIE',7);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(701,'Sucres, miels et assimilés','SOUSCATEGORIE',7);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(704,'Confitures et assimilés','SOUSCATEGORIE',7);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(801,'Glaces','SOUSCATEGORIE',8);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(803,'Desserts glacés','SOUSCATEGORIE',8);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(802,'Sorbets','SOUSCATEGORIE',8);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(901,'Beurres','SOUSCATEGORIE',9);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(905,'Autres matières grasses','SOUSCATEGORIE',9);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(902,'Huiles et graisses végétales','SOUSCATEGORIE',9);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(904,'Huiles de poissons','SOUSCATEGORIE',9);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(903,'Margarines','SOUSCATEGORIE',9);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1007,'Algues','SOUSCATEGORIE',10);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1006,'Herbes','SOUSCATEGORIE',10);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1010,'Ingrédients divers','SOUSCATEGORIE',10);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1008,'Denrées destinées à une alimentation particulière','SOUSCATEGORIE',10);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1003,'Aides culinaires','SOUSCATEGORIE',10);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1005,'Épices','SOUSCATEGORIE',10);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1002,'Condiments','SOUSCATEGORIE',10);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1001,'Sauces','SOUSCATEGORIE',10);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1004,'Sels','SOUSCATEGORIE',10);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1104,'Céréales et biscuits infantiles','SOUSCATEGORIE',11);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1101,'Laits et boissons infantiles','SOUSCATEGORIE',11);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1103,'Desserts infantiles','SOUSCATEGORIE',11);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(1102,'Petits pots salés et plats infantiles','SOUSCATEGORIE',11);
-- ---------------------------------------------------------------------------
-- ------------------------- CHILD CHILD CATEGORIES -------------------------
-- ---------------------------------------------------------------------------
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10308,'Plats de fromage','SOUSSOUSCATEGORIE',103);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10309,'Plats végétariens','SOUSSOUSCATEGORIE',103);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10306,'Plats de légumes/légumineuses','SOUSSOUSCATEGORIE',103);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10600,'Non spécialisable','SOUSSOUSCATEGORIE',106);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10301,'Plats de viande sans garniture','SOUSSOUSCATEGORIE',103);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10307,'Plats de céréales/pâtes','SOUSSOUSCATEGORIE',103);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10303,'Plats de viande et légumes/légumineuses','SOUSSOUSCATEGORIE',103);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10200,'Non spécialisable','SOUSSOUSCATEGORIE',102);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10304,'Plats de poisson sans garniture','SOUSSOUSCATEGORIE',103);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10500,'Non spécialisable','SOUSSOUSCATEGORIE',105);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10400,'Non spécialisable','SOUSSOUSCATEGORIE',104);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10100,'Non spécialisable','SOUSSOUSCATEGORIE',101);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10302,'Plats de viande et féculents','SOUSSOUSCATEGORIE',103);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(10305,'Plats de poisson et féculents','SOUSSOUSCATEGORIE',103);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20403,'Fruits appertisés','SOUSSOUSCATEGORIE',204);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20405,'Fruits et leurs produits de la martinique','SOUSSOUSCATEGORIE',204);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20401,'Fruits crus','SOUSSOUSCATEGORIE',204);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20404,'Fruits séchés','SOUSSOUSCATEGORIE',204);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20500,'Non spécialisable','SOUSSOUSCATEGORIE',205);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20406,'Fruits et leurs produits de la réunion','SOUSSOUSCATEGORIE',204);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20102,'Légumes cuits','SOUSSOUSCATEGORIE',201);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20101,'Légumes crus','SOUSSOUSCATEGORIE',201);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20104,'Légumes et leurs produits de la martinique','SOUSSOUSCATEGORIE',201);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20200,'Non spécialisable','SOUSSOUSCATEGORIE',202);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20105,'Légumes et leurs produits de la réunion','SOUSSOUSCATEGORIE',201);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20103,'Légumes séchés ou déshydratés','SOUSSOUSCATEGORIE',201);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20402,'Compotes et assimilés','SOUSSOUSCATEGORIE',204);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20302,'Légumineuses fraîches','SOUSSOUSCATEGORIE',203);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20301,'Légumineuses cuites','SOUSSOUSCATEGORIE',203);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(20303,'Légumineuses sèches','SOUSSOUSCATEGORIE',203);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(30102,'Pâtes, riz et céréales crus','SOUSSOUSCATEGORIE',301);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(30501,'Farines','SOUSSOUSCATEGORIE',305);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(30201,'Pains','SOUSSOUSCATEGORIE',302);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(30202,'Biscottes et pains grillés','SOUSSOUSCATEGORIE',302);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(30300,'Non spécialisable','SOUSSOUSCATEGORIE',303);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(30101,'Pâtes, riz et céréales cuits','SOUSSOUSCATEGORIE',301);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(30502,'Pâtes','SOUSSOUSCATEGORIE',305);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40900,'Non spécialisable','SOUSSOUSCATEGORIE',409);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40105,'Agneau et mouton casher','SOUSSOUSCATEGORIE',401);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40205,'Agneau et mouton','SOUSSOUSCATEGORIE',402);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40600,'Non spécialisable','SOUSSOUSCATEGORIE',406);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40308,'Autres spécialités charcutières','SOUSSOUSCATEGORIE',403);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40500,'Non spécialisable','SOUSSOUSCATEGORIE',405);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40700,'Non spécialisable','SOUSSOUSCATEGORIE',407);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40107,'Autres viandes','SOUSSOUSCATEGORIE',401);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40201,'Bœuf et veau','SOUSSOUSCATEGORIE',402);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40400,'Non spécialisable','SOUSSOUSCATEGORIE',404);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40101,'Bœuf et veau halal','SOUSSOUSCATEGORIE',401);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(41100,'Non spécialisable','SOUSSOUSCATEGORIE',411);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40800,'Non spécialisable','SOUSSOUSCATEGORIE',408);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40207,'Autres viandes casher','SOUSSOUSCATEGORIE',402);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40206,'Gibier','SOUSSOUSCATEGORIE',402);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40208,'Abats','SOUSSOUSCATEGORIE',402);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40108,'Abats halal','SOUSSOUSCATEGORIE',401);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40304,'Saucisses et assimilés','SOUSSOUSCATEGORIE',403);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40300,'Non spécialisable','SOUSSOUSCATEGORIE',403);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40305,'Pâtés et terrines','SOUSSOUSCATEGORIE',403);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40302,'Jambons secs et crus','SOUSSOUSCATEGORIE',403);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40301,'Jambons cuits','SOUSSOUSCATEGORIE',403);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40204,'Dinde','SOUSSOUSCATEGORIE',402);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40104,'Dinde casher','SOUSSOUSCATEGORIE',401);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40106,'Gibier casher','SOUSSOUSCATEGORIE',401);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(41002,'Œufs crus','SOUSSOUSCATEGORIE',410);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(41001,'Œufs cuits','SOUSSOUSCATEGORIE',410);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(41003,'Omelettes et autres ovoproduits','SOUSSOUSCATEGORIE',410);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40202,'Porc cru','SOUSSOUSCATEGORIE',402);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40102,'Porc','SOUSSOUSCATEGORIE',401);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40203,'Poulet','SOUSSOUSCATEGORIE',402);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40103,'Poulet halal','SOUSSOUSCATEGORIE',401);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40309,'Substituts de charcuteries pour végétariens','SOUSSOUSCATEGORIE',403);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40307,'Quenelles','SOUSSOUSCATEGORIE',403);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40306,'Rillettes','SOUSSOUSCATEGORIE',403);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40303,'Saucisson secs','SOUSSOUSCATEGORIE',403);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(40100,'Non spécialisable','SOUSSOUSCATEGORIE',401);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50303,'Fromages à pâte pressée','SOUSSOUSCATEGORIE',503);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50302,'Fromages à pâte persillée','SOUSSOUSCATEGORIE',503);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50201,'Yaourts et spécialités laitières type yaourt','SOUSSOUSCATEGORIE',502);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50301,'Fromages à pâte molle','SOUSSOUSCATEGORIE',503);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50304,'Fromage fondus','SOUSSOUSCATEGORIE',503);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50204,'Autres desserts','SOUSSOUSCATEGORIE',502);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50203,'Desserts lactés','SOUSSOUSCATEGORIE',502);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50400,'Non spécialisable','SOUSSOUSCATEGORIE',504);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50205,'Desserts végétaux','SOUSSOUSCATEGORIE',502);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50202,'Fromages blancs','SOUSSOUSCATEGORIE',502);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50305,'Autres fromages et spécialités','SOUSSOUSCATEGORIE',503);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50300,'Non spécialisable','SOUSSOUSCATEGORIE',503);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50101,'Laits de vaches liquides (non concentrés)','SOUSSOUSCATEGORIE',501);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50103,'Laits de vache concentrés ou en poudre','SOUSSOUSCATEGORIE',501);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50102,'Laits autres que de vache','SOUSSOUSCATEGORIE',501);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(50306,'Substituts de fromages pour végétariens','SOUSSOUSCATEGORIE',503);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60303,'Liqueurs et alcools','SOUSSOUSCATEGORIE',603);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60302,'Bières et cidres','SOUSSOUSCATEGORIE',603);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60205,'Boissons végétales','SOUSSOUSCATEGORIE',602);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60203,'Boissons rafraîchissantes sans alcool','SOUSSOUSCATEGORIE',602);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60204,'Boissons rafraîchissantes lactées','SOUSSOUSCATEGORIE',602);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60206,'Café, thé, cacao etc. prêts à consommer','SOUSSOUSCATEGORIE',602);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60207,'Boissons à reconstituer','SOUSSOUSCATEGORIE',602);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60301,'Vins','SOUSSOUSCATEGORIE',603);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60304,'Cocktails','SOUSSOUSCATEGORIE',603);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60100,'Non spécialisable','SOUSSOUSCATEGORIE',601);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60201,'Jus','SOUSSOUSCATEGORIE',602);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(60202,'Nectars','SOUSSOUSCATEGORIE',602);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(70900,'Non spécialisable','SOUSSOUSCATEGORIE',709);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(70200,'Non spécialisable','SOUSSOUSCATEGORIE',702);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(70600,'Non spécialisable','SOUSSOUSCATEGORIE',706);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(70800,'Non spécialisable','SOUSSOUSCATEGORIE',708);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(70700,'Non spécialisable','SOUSSOUSCATEGORIE',707);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(70300,'Non spécialisable','SOUSSOUSCATEGORIE',703);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(70500,'Non spécialisable','SOUSSOUSCATEGORIE',705);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(70100,'Non spécialisable','SOUSSOUSCATEGORIE',701);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(70400,'Non spécialisable','SOUSSOUSCATEGORIE',704);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(80100,'Non spécialisable','SOUSSOUSCATEGORIE',801);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(80300,'Non spécialisable','SOUSSOUSCATEGORIE',803);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(80200,'Non spécialisable','SOUSSOUSCATEGORIE',802);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(90100,'Non spécialisable','SOUSSOUSCATEGORIE',901);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(90500,'Non spécialisable','SOUSSOUSCATEGORIE',905);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(90200,'Non spécialisable','SOUSSOUSCATEGORIE',902);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(90400,'Non spécialisable','SOUSSOUSCATEGORIE',904);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(90300,'Non spécialisable','SOUSSOUSCATEGORIE',903);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100700,'Non spécialisable','SOUSSOUSCATEGORIE',1007);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100602,'Herbes séchées','SOUSSOUSCATEGORIE',1006);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100601,'Herbes fraîches','SOUSSOUSCATEGORIE',1006);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(101000,'Non spécialisable','SOUSSOUSCATEGORIE',1010);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100800,'Non spécialisable','SOUSSOUSCATEGORIE',1008);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100300,'Non spécialisable','SOUSSOUSCATEGORIE',1003);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100500,'Non spécialisable','SOUSSOUSCATEGORIE',1005);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100200,'Non spécialisable','SOUSSOUSCATEGORIE',1002);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100101,'Sauces condimentaires','SOUSSOUSCATEGORIE',1001);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100102,'Sauces chaudes','SOUSSOUSCATEGORIE',1001);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100103,'Sauces sucrées','SOUSSOUSCATEGORIE',1001);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100400,'Non spécialisable','SOUSSOUSCATEGORIE',1004);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(100100,'Non spécialisable','SOUSSOUSCATEGORIE',1001);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(110400,'Non spécialisable','SOUSSOUSCATEGORIE',1104);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(110100,'Non spécialisable','SOUSSOUSCATEGORIE',1101);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(110300,'Non spécialisable','SOUSSOUSCATEGORIE',1103);
INSERT INTO CATEGORIE(id_categorie, nom_categorie, type_categorie, id_categorie_parent) VALUES(110200,'Non spécialisable','SOUSSOUSCATEGORIE',1102);
