INSERT INTO SONDAGE (nom,prenom,mail,code_postal,ville,date_reponse) VALUES ('Véronique','Ruiz','veronique.ruiz@gmail.com','45740','Seguin','2023-03-25');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,18066);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,27003);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,27016);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26039);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,25218);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,15023);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,28502);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,23525);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,4008);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,18900);

INSERT INTO SONDAGE (nom,prenom,mail,code_postal,ville,date_reponse) VALUES ('Isaac','Pires','isaac.pires@gmail.com','21160','Bousquet','2023-03-25');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,5216);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,32017);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,25010);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,10099);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,20589);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,28004);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,13171);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,30130);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,25159);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,9863);

INSERT INTO SONDAGE (nom,prenom,mail,code_postal,ville,date_reponse) VALUES ('Jules','Benoit','jules.benoit@gmail.com','62390','Chauveaudan','2023-03-25');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,20114);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,10000);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,25123);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,31054);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,14000);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,8742);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,16200);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26101);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,13186);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,20054);

INSERT INTO SONDAGE (nom,prenom,mail,code_postal,ville,date_reponse) VALUES ('Agnès','de','agnes.de@gmail.com','62510','Grondinboeuf','2023-03-25');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,20163);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,2377);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,7525);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,30125);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,39400);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,24300);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,16415);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,40062);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,22000);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,19852);

INSERT INTO SONDAGE (nom,prenom,mail,code_postal,ville,date_reponse) VALUES ('Isaac','Bailly','isaac.bailly@gmail.com','97340','MarechalBourg','2023-03-25');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,20805);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,9003);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,76090);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,20301);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,32110);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,19678);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,28480);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,13122);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,13029);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,76091);

INSERT INTO SONDAGE (nom,prenom,mail,code_postal,ville,date_reponse) VALUES ('Roger','Dumont','roger.dumont@gmail.com','57280','Leclerc','2023-03-25');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,24056);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,76082);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,17020);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,11062);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,30742);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,20817);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,4016);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,7118);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,19689);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,18352);

INSERT INTO SONDAGE (nom,prenom,mail,code_postal,ville,date_reponse) VALUES ('Jérôme','Imbert-Bernier','jerome.imbert-bernier@gmail.com','87240','Blin','2023-03-25');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26047);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,32031);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,18107);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,39522);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,24659);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,9874);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26248);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,25464);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,24690);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,9621);

INSERT INTO SONDAGE (nom,prenom,mail,code_postal,ville,date_reponse) VALUES ('Adrien','Adam-Maillard','adrien.adam-maillard@gmail.com','29560','Devaux','2023-03-25');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,20062);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,9341);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26269);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26147);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,13413);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26009);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,42605);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,25574);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,11192);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,36300);

INSERT INTO SONDAGE (nom,prenom,mail,code_postal,ville,date_reponse) VALUES ('Aurélie','Schneider-Barbier','aurelie.schneider-barbier@gmail.com','76320','Briand','2023-03-25');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,23800);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,1026);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,30005);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,24679);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26041);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,16080);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26273);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,22011);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,36036);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,7425);

INSERT INTO SONDAGE (nom,prenom,mail,code_postal,ville,date_reponse) VALUES ('Guillaume','Tanguy','guillaume.tanguy@gmail.com','59179','Carre','2023-03-25');
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,19250);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,13167);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,40105);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,39218);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,18012);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,20543);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,19120);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26090);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,5009);
INSERT INTO CHOIX_ALIMENTS_SONDAGE (id_personne,id_aliment) VALUES ((SELECT MAX(id_personne) FROM SONDAGE) ,26210);

