DROP TABLE SOUSSOUSCATEGORIE;
DROP TABLE SOUSCATEGORIE;
DROP TABLE CATEGORIE;

CREATE OR REPLACE TABLE CATEGORIE (
    IdCategorie INTEGER PRIMARY KEY,
    NomCategorie VARCHAR(30)
);

CREATE OR REPLACE TABLE SOUSCATEGORIE (
    IdSousCategorie INTEGER PRIMARY KEY,
    IdCategorie INTEGER,
    NomSousCategorie VARCHAR(30),
    CONSTRAINT FK_SousCategorie_Categorie
        FOREIGN KEY (IdCategorie) REFERENCES CATEGORIE(IdCategorie)
);

CREATE OR REPLACE TABLE SOUSSOUSCATEGORIE (
    IdSousSousCategorie INTEGER PRIMARY KEY,
    IdSousCategorie INTEGER,
    NomSousSousCategorie VARCHAR(30),
    CONSTRAINT FK_SousSousCategorie_SousCategorie
        FOREIGN KEY (IdSousCategorie) REFERENCES SOUSCATEGORIE(IdSousCategorie)
);